### PR TITLE
Add torch force update function to use in lua

### PR DESCRIPTION
**Pull request by VodoXleb**
Can be useful if we want to have torch working on  corpses for example

### CODE REVIEW

**Comment by themrdemonized** [comment]
The comments got fucked up, as usual. Are you using VS 2022 ?

**Comment by VodoXleb** [comment]
I use VSCode, can that be a problem? 
(+ Github desktop) 
Sorry for inconveniences

**Comment by themrdemonized** [comment]
yes, look at your PR, it has all comments messed up. Use VS 2022 next time. Or make sure your commits dont have parts you havent changed

**Comment by VodoXleb** [comment]
Ok I see, thanks

**Pull request merged**
