### PR TITLE
Disable ogg-comment logging in MASTER_GOLD.

### PR DESCRIPTION
**Pull request by MagielBruntink**

### CODE REVIEW

**Comment by themrdemonized** [comment]
What is the point of this change?

**Comment by MagielBruntink** [comment]
Cleaning up the console and the log file. These ogg comment warnings really mess up both of those.

**Comment by themrdemonized** [comment]
Those are pretty useful for modders, and using that directive will remove them entirely. If you want them to be displayed only in debug mode, instead of directive use `strstr(Core.Params, "-dbg")`

**Comment by MagielBruntink** [comment]
Closing, new approach in https://github.com/themrdemonized/xray-monolith/pull/23

**Pull request closed without merging**
